Repository awslabs/aws-ddk, pull requests merged in 2022-08, with the labels that each got.

#136 feat: Set up project metadata
  .gitattributes
  .github/workflows/release.yml
  .github/workflows/upgrade.yml
  .gitignore
  .npmignore
  .projen/deps.json
  .projen/files.json
  .projen/tasks.json
  .projenrc.js
  API.md
  package.json
  yarn.lock
Labels: work-in-progress, workflows, typescript

#138 feat: Created DataStage, DataPipeline and SQSToLambda constructs
  .projenrc.js
  API.md
  src/index.ts
  src/pipelines/index.ts
  src/pipelines/pipelines.ts
  src/pipelines/stage.ts
  src/stages/index.ts
  src/stages/sqs-lambda.ts
  test/data-pipelines.test.ts
  test/hello.test.ts
  test/sqs-lambda-stage.test.ts
Labels: typescript

#139 feat: Adding core.cicd
  API.md
  src/cicd/actions.ts
  src/cicd/index.ts
  src/cicd/pipelines.ts
  src/cicd/utils.ts
  src/index.ts
  test/cicd-pipeline-stack.test.ts
Labels: core, typescript

#143 feat: Implement S3EventStage in Typescript
  API.md
  src/pipelines/pipelines.ts
  src/pipelines/stage.ts
  src/stages/index.ts
  src/stages/s3-event.ts
  test/data-pipelines.test.ts
  test/s3-event.test.ts
Labels: typescript

#146 feat: Implement BaseStack in Typescript
  API.md
  src/base/index.ts
  src/base/stack.ts
  src/index.ts
  test/base-stack.test.ts
Labels: typescript

#145 feat: athena sql stage
  .projen/deps.json
  .projenrc.js
  API.md
  package-lock.json
  package.json
  src/pipelines/stage.ts
  src/stages/athena-sql.ts
  src/stages/index.ts
  test/athena-sql-stage.test.ts
  test/cicd-pipeline-stack.test.ts
  yarn.lock
Labels: core, dependencies, typescript

#148 feat: Add support for Python in JSII and upgrade CDK version
  .github/workflows/build.yml
  .mergify.yml
  .projen/deps.json
  .projen/tasks.json
  .projenrc.js
  API.md
  package.json
  yarn.lock
Labels: core, dependencies, typescript

#149 fix: Fix typescript s3 event pattern
  src/stages/s3-event.ts
  test/s3-event.test.ts
Labels: bug, core

#154 chore: Setting up Prettier code formatting
  .eslintrc.json
  .gitattributes
  .gitignore
  .prettierignore
  .prettierrc.json
  .projen/deps.json
  .projen/files.json
  .projenrc.js
  package.json
  src/cicd/actions.ts
  src/cicd/pipelines.ts
  src/cicd/utils.ts
  src/pipelines/index.ts
  src/pipelines/pipelines.ts
  src/pipelines/stage.ts
  src/stages/athena-sql.ts
  src/stages/index.ts
  src/stages/s3-event.ts
  src/stages/sqs-lambda.ts
  test/athena-sql-stage.test.ts
  test/cicd-pipeline-stack.test.ts
  test/data-pipelines.test.ts
  test/s3-event.test.ts
  test/sqs-lambda-stage.test.ts
  yarn.lock
Labels: typescript

#152 feat: Typescript conversion of `GlueTransformStage`
  .projenrc.js
  API.md
  src/stages/glue-transform.ts
  src/stages/index.ts
  test/glue-transform-stage.test.ts
Labels: core, feature-request, effort/medium

#151 feat: Add FirehoseToS3Stage and tests
  .gitignore
  .projen/deps.json
  .projen/tasks.json
  .projenrc.js
  API.md
  package.json
  src/core/kinesis-firehose-defaults.ts
  src/core/s3-defaults.ts
  src/core/utils.ts
  src/stages/index.ts
  src/stages/kinesis-s3.ts
  test/data-pipelines.test.ts
  test/kinesis-s3-stage.test.ts
  yarn.lock
Labels: feature-request, effort/medium
