Repository awslabs/aws-ddk, pull requests merged in 2023-01, with the labels that each got.

#204 Enhancing AthenaSQLStage to handle both static and dynamic SQL Queries
  core/aws_ddk_core/stages/athena_sql.py
  core/tests/unit/test_athena_sql_stage.py
Labels: enhancement, core

#207 Enhancement: adding `queue_props` to `SqsToLambda`
  core/aws_ddk_core/stages/sqs_lambda.py
  core/tests/unit/test_sqs_lambda_stage.py
Labels: enhancement, core

#209 Enhancement: adding `rule_name` parameter to `DataPipeline.add_stage()`
  core/aws_ddk_core/pipelines/pipeline.py
  core/tests/unit/test_basic_data_pipeline.py
Labels: enhancement, core

#208 Enhancing GlueTransform Stage for Stepfunction Crawler Task Retry
  core/aws_ddk_core/stages/glue_transform.py
Labels: enhancement, core

#210 Enhancment: Adding additonal sfn props support to `StateMachineStage`
  core/aws_ddk_core/pipelines/stage.py
  core/aws_ddk_core/stages/appflow_ingestion.py
  core/aws_ddk_core/stages/athena_sql.py
  core/aws_ddk_core/stages/databrew_transform.py
  core/aws_ddk_core/stages/glue_transform.py
  core/tests/unit/test_appflow_stage.py
  core/tests/unit/test_athena_sql_stage.py
  core/tests/unit/test_databrew_transform_stage.py
  core/tests/unit/test_glue_transform_stage.py
Labels: enhancement, core

#211 Fix bug for context_layer undefined and changing region_name derived from boto3 session
  core/aws_ddk_core/resources/_utils.py
Labels: bug, core

#205 Enhancement: Allowing alarms to be disabled in stages
  core/aws_ddk_core/pipelines/stage.py
  core/aws_ddk_core/stages/appflow_ingestion.py
  core/aws_ddk_core/stages/athena_sql.py
  core/aws_ddk_core/stages/databrew_transform.py
  core/aws_ddk_core/stages/dms_s3_to_s3.py
  core/aws_ddk_core/stages/glue_transform.py
  core/aws_ddk_core/stages/kinesis_s3.py
  core/aws_ddk_core/stages/sqs_lambda.py
  core/tests/unit/test_appflow_stage.py
  core/tests/unit/test_athena_sql_stage.py
  core/tests/unit/test_databrew_transform_stage.py
  core/tests/unit/test_glue_transform_stage.py
  core/tests/unit/test_sqs_lambda_stage.py
Labels: enhancement, core

#222 feat: appflow ingestion stage
  .projen/deps.json
  .projenrc.js
  API.md
  package-lock.json
  package.json
  src/stages/appflow-ingestion.ts
  src/stages/index.ts
  src/stages/lambda_handlers/appflow_check_flow_status/__init__.py
  src/stages/lambda_handlers/appflow_check_flow_status/lambda_function.py
  test/appflow-ingestion-stage.test.ts
  yarn.lock
Labels: core, testing, typescript

#224 feat: `DataBrewTranformStage`
  API.md
  src/stages/databrew-transform.ts
  src/stages/index.ts
  test/databrew-transform-stage.test.ts
Labels: core, feature-request, typescript

#226 feat: Add `schedule` support to `DataPipeline.add_stage()`
  API.md
  src/pipelines/pipelines.ts
  test/data-pipelines.test.ts
Labels: core, typescript

#227 chore: Increase Coverage of TS tests
  API.md
  src/cicd/pipelines.ts
  src/stages/sqs-lambda.ts
  test/athena-sql-stage.test.ts
  test/cicd-pipeline-stack.test.ts
  test/data-pipelines.test.ts
  test/glue-transform-stage.test.ts
  test/sqs-lambda-stage.test.ts
Labels: testing, typescript

#228 chore: Add `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation, typescript

#230 feat: appflow stage refactor
  API.md
  src/stages/appflow-ingestion.ts
  test/appflow-ingestion-stage.test.ts
Labels: enhancement, typescript

#233 feat: resource naming refactor
  API.md
  src/pipelines/stage.ts
  src/stages/kinesis-s3.ts
  src/stages/sqs-lambda.ts
  test/athena-sql-stage.test.ts
  test/cicd-pipeline-stack.test.ts
  test/data-pipelines.test.ts
  test/sqs-lambda-stage.test.ts
Labels: enhancement, core, typescript

#235 feat: Integration Testing
  .eslintrc.json
  .github/workflows/build.yml
  .github/workflows/pull-request-lint.yml
  .github/workflows/upgrade.yml
  .gitignore
  .npmignore
  .projen/deps.json
  .projen/tasks.json
  .projenrc.js
  CONTRIBUTING.md
  integ/integ.kinesis-s3-stage.test.ts
  integ/integ.s3-event.test.ts
  package-lock.json
  package.json
  yarn.lock
Labels: testing
