Repository awslabs/aws-ddk, pull requests merged in 2023-08, with the labels that each got.

#418 fix: Making 'configPath' optional in interfaces
  API.md
  src/config/configurator.ts
Labels: bug

#419 feat: Allowing 'any' in configuration props
  API.md
  src/config/configurator.ts
Labels: enhancement

#430 feat: Update MWAATriggerDagsStage to pass json event to MWAA airflow dag
  src/stages/mwaa-trigger-dags.ts
Labels: core, feature-request
