Repository awslabs/aws-ddk, pull requests merged in 2023-05, with the labels that each got.

#315 chore: Configurator refactor
  API.md
  package.json
  src/config/configurator.ts
  test/config.test.ts
  test/test-config.json
  yarn.lock
Labels: bug, enhancement, core, typescript

#318 chore: change return type of `getEnvironment` to `cdk.Environment`
  API.md
  src/config/configurator.ts
Labels: bug

#317 feat: Updating AthenaSQL stage to handle multiple queries
  API.md
  package-lock.json
  src/stages/athena-sql.ts
  test/athena-sql-stage.test.ts
Labels: enhancement, core, typescript

#319 fix: Configurator missing legacy ddk bootstrap values
  src/config/configurator.ts
  test/base-stack.test.ts
  test/test-config.json
Labels: bug, core, typescript

#326 fix: athena integration test
  docs/_layouts/default.html
  docs/index.markdown
  docs/release/latest/how-to/upgrade-guide.markdown
  integ/integ.athena-sql.test.ts
Labels: bug, testing, typescript

#328 chore: Adding SDLF workshop and workshops page to docs
  docs/_config.yml
  docs/_layouts/default.html
  docs/workshops.markdown
Labels: documentation

#331 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: dependencies

#332 chore: Adds pypi downloads badge and package links to readme
  API.md
  README.md
Labels: documentation
